name: "Validate"

on:
  pull_request_target:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  validate-labels:
    name: With PR Label action
    runs-on: ubuntu-latest
    steps:
      - name: PR Label Validation
        uses: jesusvasquez333/verify-pr-label-action@v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement'
          invalid-labels: 'help wanted, invalid, question'
          pull-request-number: '${{ github.event.pull_request.number }}'